### ISSUE TITLE
iconv dependency

### ISSUE THREAD

**Issue by stahlnow** [vindvaki/djvu2pdf#1]
great script, i had to add ruby-iconv package (arch linux) to get it to work.

**Comment by vindvaki** [comment]
Thanks for the feedback. This is probably a dependency of pdfbeads, which is written in ruby, and [has a runtime dependency on iconv](https://github.com/ifad/pdfbeads/blob/master/pdfbeads.gemspec#L30) (and, depending on how you installed pdfbeads, this should usually have been installed for you).
