### ISSUE TITLE
What's the license of the program?

### ISSUE THREAD

**Issue by rbrito** [vindvaki/djvu2pdf#2]
Hi.

For packaging purposes (I hope to file an "Request for Package" bug for inclusion in Debian or other operating systems), there must be a license for the project. What license is the project in?

Thanks for the scripts,

Rogério.

**Comment by vindvaki** [comment]
Hi @rbrito, sorry I only saw this now. Which license would make inclusion the easiest?

**Comment by rbrito** [comment]
Hi, @vindvaki.

Something like the (L)GPL or the Apache License v2 or MIT... In fact, GitHub even has a wizard to let you choose the license: https://help.github.com/articles/licensing-a-repository/

As long as everything is properly licensed and compatible with the rest of the programs, inclusion should be easy once someone shows up for maintainership.


Thanks,

Rogério.

**Comment by vindvaki** [comment]
@rbrito Done! See commit 798bc7e

**Comment by rbrito** [comment]
Excellent, then!

Closing this bug.
