### ISSUE TITLE
Does it work on windows 11?

### ISSUE THREAD

**Issue by dvogureckiy99** [vindvaki/djvu2pdf#7]
Hello,
Does it work on windows 11?
Thank you for script.

Please, can you named exactly what version of dependencies you have used and your OS?

**Comment by vindvaki** [comment]
>  Does it work on windows 11?

I do not know (I don't use Windows). I think your best bet would be to get it running under WSL or Docker.

> Please, can you named exactly what version of dependencies you have used and your OS?

No. I hope it still works, but I wrote this a very long time ago and have not used it for many years.
